# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 227fcd7f724f9ecbaa4f34a9e929d996ed68391dc2388b22dd7db9001f7456fa7ab0079adf922d255b318978191d425602be247624618bc3591710f1692daa8e

test:
  secret_key_base: be5be93fdbe1e702a142ef829d0e132501096bb03193b992eb1965758d9adf43115cfbc3c37a016f6f3f16e154cb361605efc57a5315cbfe07fadb78baee8a7f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
